services:
  - type: web
    name: painel-operacional
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: N8N_TRANSFERENCIAS_URL
        sync: false
      - key: N8N_TRANSFERENCIAS_DETALHE_URL
        sync: false
      - key: N8N_PERFORMANCE_PORTADORES_URL
        sync: false
      - key: N8N_PERFORMANCE_ROMANEIO_DETALHE_URL
        sync: false
      - key: N8N_COMPOSICAO_SUBREGIOES_URL
        sync: false
